#!/usr/bin/env python3
"""Build script for BBC Micro line rasterizer demo and Battlezone game.

Usage:
    python3 build.py          # build demo (assembles demo.s, creates demo.ssd)
    python3 build.py game     # build game (generates tables, assembles game.s,
                              #             creates game.ssd, compiles emu)
"""

import subprocess
import sys
import os
import struct
import math

SECTOR_SIZE = 256
TRACKS = 40
SECTORS_PER_TRACK = 10
TOTAL_SECTORS = TRACKS * SECTORS_PER_TRACK   # 400

DEMO_LOAD = 0x1800
DEMO_EXEC = 0x1800


def assemble(src, binfile, objfile=None, extra_flags=None):
    """Assemble a .s file → .bin via ca65 + ld65."""
    if objfile is None:
        objfile = src.replace(".s", ".o")
    print(f"Assembling {src} ...")

    cmd = ["ca65", "--cpu", "65C02", "-g"]
    if extra_flags:
        cmd.extend(extra_flags)
    cmd.extend([src, "-o", objfile])
    r = subprocess.run(
        cmd,
        capture_output=True, text=True,
    )
    if r.returncode != 0:
        print("ca65 failed:\n" + r.stderr)
        sys.exit(1)

    dbgfile = binfile.replace(".bin", ".dbg")
    lblfile = binfile.replace(".bin", ".labels")
    r = subprocess.run(
        ["ld65", "-C", "linker.cfg", "--dbgfile", dbgfile, objfile, "-o", binfile],
        capture_output=True, text=True,
    )
    if r.returncode != 0:
        print("ld65 failed:\n" + r.stderr)
        sys.exit(1)

    os.remove(objfile)

    # Extract labels from debug file → VICE format .labels file
    import re
    with open(dbgfile) as df:
        syms = []
        for line in df:
            if line.startswith("sym\t"):
                m_name = re.search(r'name="([^"]+)"', line)
                m_val = re.search(r'val=(0x[0-9A-Fa-f]+)', line)
                m_type = re.search(r'type=(\w+)', line)
                if m_name and m_val and m_type and m_type.group(1) == "lab":
                    name = m_name.group(1)
                    if name.startswith("@"):
                        continue  # skip local/anonymous labels
                    addr = int(m_val.group(1), 16)
                    syms.append((addr, name))
        syms.sort()
        with open(lblfile, "w") as lf:
            for addr, name in syms:
                lf.write(f"al {addr:06X} .{name}\n")
    os.remove(dbgfile)
    print(f"  {lblfile}: {len(syms)} labels")

    size = os.path.getsize(binfile)
    print(f"  {binfile}: {size} bytes")
    return size


def create_ssd(binfile, ssdfile, title=b"LineDEMO", progname=b"DEMO   "):
    """Create an auto-booting DFS disk image containing !BOOT and the binary."""
    bin_size = os.path.getsize(binfile)
    print(f"Creating {ssdfile} ...")

    with open(binfile, "rb") as f:
        bin_data = f.read()

    boot_content = b"*RUN " + progname.strip() + b"\r"
    boot_len = len(boot_content)

    boot_sector = 2
    prog_sector = 3
    prog_sectors = (bin_size + SECTOR_SIZE - 1) // SECTOR_SIZE

    disk = bytearray(TOTAL_SECTORS * SECTOR_SIZE)

    # Sector 0: catalogue names
    disk[0x000:0x000 + len(title)] = title[:8]

    # Entry 0: !BOOT
    disk[0x008:0x00F] = b"!BOOT  "
    disk[0x00F] = ord("$")

    # Entry 1: program
    disk[0x010:0x017] = progname[:7]
    disk[0x017] = ord("$")

    # Sector 1: catalogue attributes
    disk[0x104] = 0x00
    disk[0x105] = 2 * 8
    disk[0x106] = (3 << 4) | ((TOTAL_SECTORS >> 8) & 0x03)
    disk[0x107] = TOTAL_SECTORS & 0xFF

    # Entry 0 (!BOOT)
    struct.pack_into("<HH", disk, 0x108, 0x0000, 0x0000)
    struct.pack_into("<H",  disk, 0x10C, boot_len)
    disk[0x10E] = 0x00
    disk[0x10F] = boot_sector

    # Entry 1 (program)
    struct.pack_into("<HH", disk, 0x110, DEMO_LOAD, DEMO_EXEC)
    struct.pack_into("<H",  disk, 0x114, bin_size)
    disk[0x116] = 0x00
    disk[0x117] = prog_sector

    # File data
    off = boot_sector * SECTOR_SIZE
    disk[off:off + boot_len] = boot_content

    off = prog_sector * SECTOR_SIZE
    disk[off:off + len(bin_data)] = bin_data

    with open(ssdfile, "wb") as f:
        f.write(disk)

    print(f"  {ssdfile}: {len(disk)} bytes  "
          f"({2 + 1 + prog_sectors} sectors used)")


def generate_tables():
    """Generate sin/cos/recip lookup tables as ca65 .byte directives."""
    print("Generating tables.inc ...")

    lines = []
    lines.append("; tables.inc — generated by build.py, do not edit")
    lines.append("")

    # Sin table: 256 entries, sin(i * 2pi / 256) * 127, signed
    # Index 0..255 maps to angle 0..2pi
    lines.append("; sin_table: 256 entries, signed (-127..+127)")
    lines.append("; sin_table[i] = round(sin(i * 2*pi / 256) * 127)")
    lines.append("sin_table:")
    sin_vals = []
    for i in range(256):
        angle = i * 2.0 * math.pi / 256.0
        val = round(math.sin(angle) * 127.0)
        val = max(-127, min(127, val))
        sin_vals.append(val & 0xFF)
    for row in range(0, 256, 16):
        chunk = sin_vals[row:row+16]
        lines.append("    .byte " + ", ".join(f"${v:02X}" for v in chunk))

    lines.append("")

    # Cos table: 256 entries, cos(i * 2pi / 256) * 127, signed
    lines.append("; cos_table: 256 entries, signed (-127..+127)")
    lines.append("; cos_table[i] = round(cos(i * 2*pi / 256) * 127)")
    lines.append("cos_table:")
    cos_vals = []
    for i in range(256):
        angle = i * 2.0 * math.pi / 256.0
        val = round(math.cos(angle) * 127.0)
        val = max(-127, min(127, val))
        cos_vals.append(val & 0xFF)
    for row in range(0, 256, 16):
        chunk = cos_vals[row:row+16]
        lines.append("    .byte " + ", ".join(f"${v:02X}" for v in chunk))

    lines.append("")

    # Reciprocal table: K=8, 256 entries covering z=2.000 to z=33.875
    # index = (z - 1) * 8 + frac>>5, recip[i] = min(127, round(128 / (1 + i/8)))
    lines.append("; recip_table: K=8, 256 entries, z=1.000..32.875 eighth-unit resolution")
    lines.append("; index = (vz-1)*8 + (vz_frac>>5), recip[i] = min(127, round(128/(1+i/8)))")
    lines.append("recip_table:")
    recip_vals = []
    for i in range(256):
        z = 1.0 + i / 8.0
        val = min(127, round(128.0 / z))
        recip_vals.append(val)
    for row in range(0, 256, 16):
        chunk = recip_vals[row:row+16]
        lines.append("    .byte " + ", ".join(f"${v:02X}" for v in chunk))

    lines.append("")

    # Reciprocal fractional correction table (K=8)
    lines.append("; recip_lo_table: fractional correction for recip_table (K=8)")
    lines.append("; recip_lo[i] = round((ideal - rounded) * 128), signed")
    lines.append("recip_lo_table:")
    recip_lo_vals = []
    for i in range(256):
        z = 1.0 + i / 8.0
        ideal = 128.0 / z
        rounded = min(127, round(ideal))
        error = ideal - rounded
        correction = round(error * 128)
        correction = max(-64, min(63, correction))
        recip_lo_vals.append(correction & 0xFF)
    for row in range(0, 256, 16):
        chunk = recip_lo_vals[row:row+16]
        lines.append("    .byte " + ", ".join(f"${v:02X}" for v in chunk))

    lines.append("")

    # Quarter-square tables for fast multiply: sqr[i] = floor(i*i/4)
    lines.append("; sqr_lo: quarter-square table low byte, sqr_lo[i] = floor(i*i/4) & $FF")
    lines.append("sqr_lo:")
    sqr_lo_vals = []
    for i in range(256):
        val = (i * i) // 4
        sqr_lo_vals.append(val & 0xFF)
    for row in range(0, 256, 16):
        chunk = sqr_lo_vals[row:row+16]
        lines.append("    .byte " + ", ".join(f"${v:02X}" for v in chunk))

    lines.append("")

    lines.append("; sqr_hi: quarter-square table high byte, sqr_hi[i] = floor(i*i/4) >> 8")
    lines.append("sqr_hi:")
    sqr_hi_vals = []
    for i in range(256):
        val = (i * i) // 4
        sqr_hi_vals.append((val >> 8) & 0xFF)
    for row in range(0, 256, 16):
        chunk = sqr_hi_vals[row:row+16]
        lines.append("    .byte " + ", ".join(f"${v:02X}" for v in chunk))

    lines.append("")

    # Quarter-square overflow tables for i=256..511 (unsigned multiply sum overflow)
    lines.append("; sqr2_lo: quarter-square overflow table low byte, sqr2_lo[i] = floor((i+256)^2/4) & $FF")
    lines.append("sqr2_lo:")
    for row in range(0, 256, 16):
        chunk = []
        for j in range(16):
            i = row + j
            val = ((i + 256) * (i + 256)) // 4
            chunk.append(val & 0xFF)
        lines.append("    .byte " + ", ".join(f"${v:02X}" for v in chunk))

    lines.append("")

    lines.append("; sqr2_hi: quarter-square overflow table high byte, sqr2_hi[i] = floor((i+256)^2/4) >> 8")
    lines.append("sqr2_hi:")
    for row in range(0, 256, 16):
        chunk = []
        for j in range(16):
            i = row + j
            val = ((i + 256) * (i + 256)) // 4
            chunk.append((val >> 8) & 0xFF)
        lines.append("    .byte " + ", ".join(f"${v:02X}" for v in chunk))

    lines.append("")

    with open("tables.inc", "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"  tables.inc: {len(lines)} lines")


def compile_emu():
    """Compile emu.c using cc + SDL2."""
    print("Compiling emu.c ...")

    # Get SDL2 flags
    try:
        cflags = subprocess.check_output(
            ["sdl2-config", "--cflags"], text=True).strip()
        libs = subprocess.check_output(
            ["sdl2-config", "--libs"], text=True).strip()
    except FileNotFoundError:
        print("Error: sdl2-config not found. Install SDL2: brew install sdl2")
        sys.exit(1)

    cmd = f"cc -O2 -o emu emu.c -Itools {cflags} {libs}"
    print(f"  {cmd}")
    r = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if r.returncode != 0:
        print("Compilation failed:\n" + r.stderr)
        sys.exit(1)

    print("  emu compiled successfully")


def build_demo():
    """Build the demo (original behaviour)."""
    demo_size = assemble("demo.s", "demo.bin")
    create_ssd("demo.bin", "demo.ssd")
    print("\nDone!  Load demo.ssd in jsbeeb and press SHIFT+BREAK to run.")


def build_game():
    """Build the Battlezone game + emulator."""
    generate_tables()
    game_size = assemble("game.s", "game.bin", "game.o",
                         extra_flags=["-DUNROLL_SHALLOW=1"])
    create_ssd("game.bin", "game.ssd", title=b"BATTLZON", progname=b"GAME   ")
    compile_emu()
    print(f"\nDone!  Run: ./emu game.bin")


if __name__ == "__main__":
    target = sys.argv[1] if len(sys.argv) > 1 else "demo"

    if target == "game":
        build_game()
    elif target == "demo":
        build_demo()
    else:
        print(f"Unknown target: {target}")
        print("Usage: python3 build.py [demo|game]")
        sys.exit(1)
