#!/usr/bin/env python3
"""Generate status bar data (logo + digit font) from header.txt.

Reads header.txt:
  - Lines 1-7: Logo (25 pixels wide, padded to 26 = 13 char cols)
  - Lines 9-15: Numeric font (10 digits, 4px each = 2 char cols per digit)

Outputs status_data.inc with:
  - logo_data: 104 bytes (13 cols × 8 scanlines), colour 1 (red)
  - font_data: 160 bytes (10 digits × 2 cols × 8 scanlines), colour 7 (white)
"""


def mode2_byte(left_col, right_col):
    """Encode two 4-bit MODE 2 colours into one byte."""
    b = 0
    for bit in range(4):
        if left_col & (1 << bit):
            b |= (1 << (bit * 2 + 1))
        if right_col & (1 << bit):
            b |= (1 << (bit * 2))
    return b


def parse_pixels(line):
    """Parse a line from header.txt into a list of pixel booleans."""
    pixels = []
    for i in range(0, len(line), 2):
        pair = line[i:i+2]
        pixels.append(pair == 'XX')
    return pixels


def main():
    with open("header.txt") as f:
        lines = [l.rstrip('\n') for l in f.readlines()]

    # Parse logo (lines 0-6, 0-indexed) — 7 rows
    logo_rows = []
    for i in range(7):
        pixels = parse_pixels(lines[i])
        # Pad to 26 pixels (13 char columns)
        while len(pixels) < 26:
            pixels.append(False)
        logo_rows.append(pixels[:26])

    # Parse font (lines 8-14, 0-indexed) — 7 rows
    font_rows = []
    for i in range(8, 15):
        pixels = parse_pixels(lines[i])
        # 10 digits × 4px = 40 pixels, pad if needed
        while len(pixels) < 40:
            pixels.append(False)
        font_rows.append(pixels[:40])

    # Encode logo: 13 char columns × 8 scanlines, colour 1 (red)
    # Scanline 0 = blank, scanlines 1-7 = content (shifted down 1 pixel)
    COL_RED = 1
    logo_bytes = []
    for col in range(13):
        for scanline in range(8):
            if scanline >= 1:
                left_px = logo_rows[scanline - 1][col * 2]
                right_px = logo_rows[scanline - 1][col * 2 + 1]
            else:
                left_px = False
                right_px = False
            left_col = COL_RED if left_px else 0
            right_col = COL_RED if right_px else 0
            logo_bytes.append(mode2_byte(left_col, right_col))

    assert len(logo_bytes) == 104, f"Logo: {len(logo_bytes)} bytes, expected 104"

    # Encode font: 10 digits × 2 char columns × 8 scanlines, colour 7 (white)
    # Scanline 0 = blank, scanlines 1-7 = content (shifted down 1 pixel)
    # Pixels shifted 1 right within cells: col0=[empty, px0], col1=[px1, px2]
    COL_WHITE = 7
    font_bytes = []
    for digit in range(10):
        for col in range(2):
            for scanline in range(8):
                if scanline >= 1:
                    row = scanline - 1
                    if col == 0:
                        left_px = False
                        right_px = font_rows[row][digit * 4]
                    else:
                        left_px = font_rows[row][digit * 4 + 1]
                        right_px = font_rows[row][digit * 4 + 2]
                else:
                    left_px = False
                    right_px = False
                left_col = COL_WHITE if left_px else 0
                right_col = COL_WHITE if right_px else 0
                font_bytes.append(mode2_byte(left_col, right_col))

    assert len(font_bytes) == 160, f"Font: {len(font_bytes)} bytes, expected 160"

    # Write assembly include
    with open("status_data.inc", "w") as f:
        f.write("; Status bar data: logo + digit font for MODE 2\n")
        f.write("; Generated by gen_status.py from header.txt\n\n")
        f.write("logo_data:\n")
        for col in range(13):
            offset = col * 8
            vals = ", ".join(f"${v:02X}" for v in logo_bytes[offset:offset+8])
            f.write(f"    .byte {vals}  ; col {col}\n")

        f.write("\nfont_data:\n")
        for digit in range(10):
            for col in range(2):
                offset = (digit * 2 + col) * 8
                vals = ", ".join(f"${v:02X}" for v in font_bytes[offset:offset+8])
                f.write(f"    .byte {vals}  ; digit {digit}, col {col}\n")

    print(f"Wrote status_data.inc (logo: {len(logo_bytes)} bytes, font: {len(font_bytes)} bytes)")


if __name__ == "__main__":
    main()
