#!/usr/bin/env python3
"""Generate 18 chains (9H + 9V) for a 9×9 perspective grid.

Uses proper 3D perspective projection with configurable camera parameters.
Height-modulated from the top-left 9×9 corner of map_data.inc.

Outputs ca65 .byte directives for grid_data (324 bytes).
"""

import math, re, os

# === Camera parameters ===
CAMERA_HEIGHT    = 20.0     # height above ground plane
CAMERA_PITCH_DEG = 30.0     # downward pitch angle in degrees
FOCAL_LENGTH     = 128.0    # focal length in pixels (controls FOV)

# === Grid parameters ===
GRID_SPACING     = 3.0      # world units between grid lines
GRID_START_DIST  = 20.0     # distance to nearest grid row
GRID_ROW_STEP    = 5.0      # distance between consecutive grid rows
GRID_SIZE        = 9        # 9×9 intersections (8×8 cells)

# === Height modulation ===
HEIGHT_SCALE     = 0.12     # world units of height per heightmap unit deviation

# === Screen ===
SCREEN_W = 128
SCREEN_H = 160
CX = SCREEN_W // 2          # 64
CY = SCREEN_H // 2          # 80

# === Derived ===
theta = math.radians(CAMERA_PITCH_DEG)
cos_t = math.cos(theta)
sin_t = math.sin(theta)


def project(wx, wy, wz):
    """Project world point (wx, wy, wz) to screen (sx, sy).

    Camera at (0, CAMERA_HEIGHT, 0), pitched down by CAMERA_PITCH_DEG.
    World: +X = right, +Y = up, +Z = forward.
    Screen: origin top-left, +X right, +Y down.
    """
    h = CAMERA_HEIGHT
    # Translate relative to camera
    rx, ry, rz = wx, wy - h, wz
    # Rotate by pitch (camera pitches down → world rotates up)
    vx = rx
    vy = ry * cos_t + rz * sin_t
    vz = -ry * sin_t + rz * cos_t
    if vz < 0.1:
        return None  # behind camera
    sx = CX + FOCAL_LENGTH * vx / vz
    sy = CY - FOCAL_LENGTH * vy / vz
    return (sx, sy)


def read_heightmap():
    """Parse map_data.inc and return list of lists."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    path = os.path.join(script_dir, "map_data.inc")
    hmap = []
    with open(path) as f:
        for line in f:
            m = re.search(r'\.byte\s+([\d,\s]+)', line)
            if m:
                vals = [int(v.strip()) for v in m.group(1).split(',') if v.strip()]
                hmap.append(vals)
    return hmap


hmap = read_heightmap()
center_h = hmap[4][4]

# Build 9×9 intersection table: pts[row][col] = (x, y)
pts = []
for row in range(GRID_SIZE):
    wz = GRID_START_DIST + row * GRID_ROW_STEP
    row_pts = []
    for col in range(GRID_SIZE):
        gx = col - (GRID_SIZE - 1) / 2   # -4 .. +4
        wx = gx * GRID_SPACING

        # Height from heightmap
        wy = 0.0
        if row < len(hmap) and col < len(hmap[row]):
            wy = (hmap[row][col] - center_h) * HEIGHT_SCALE

        result = project(wx, wy, wz)
        if result is None:
            # Fallback: place at screen edge
            row_pts.append((CX, 0))
            continue
        sx, sy = result
        x = max(0, min(127, round(sx)))
        y = max(0, min(159, round(sy)))
        row_pts.append((x, y))
    pts.append(row_pts)

# Print diagnostic info to stderr
import sys
print(f"; Camera: height={CAMERA_HEIGHT}, pitch={CAMERA_PITCH_DEG}°, "
      f"focal={FOCAL_LENGTH}", file=sys.stderr)
print(f"; Grid: spacing={GRID_SPACING}, start={GRID_START_DIST}, "
      f"step={GRID_ROW_STEP}", file=sys.stderr)
for row in range(GRID_SIZE):
    gz = row - (GRID_SIZE - 1) // 2
    near_x = pts[row][0][0]
    far_x = pts[row][-1][0]
    y = pts[row][GRID_SIZE // 2][1]
    width = far_x - near_x
    print(f";   row {row} (gz={gz:+d}): y={y}, width={width}px "
          f"({near_x}-{far_x})", file=sys.stderr)

# Taper ratio
near_width = pts[0][-1][0] - pts[0][0][0]
far_width = pts[-1][-1][0] - pts[-1][0][0]
print(f"; Taper ratio: {near_width/max(far_width,1):.1f}:1 "
      f"(near {near_width}px, far {far_width}px)", file=sys.stderr)

# Output assembly
print(f"; Generated by gen_grid.py — 18 chains (9H + 9V), 9 points each")
print(f"; Camera: height={CAMERA_HEIGHT}, pitch={CAMERA_PITCH_DEG}°, "
      f"focal={FOCAL_LENGTH}")
print(f"; Grid: spacing={GRID_SPACING}, start={GRID_START_DIST}, "
      f"step={GRID_ROW_STEP}")
print()

print("; Horizontal chains (9 rows × 9 points = 162 bytes)")
for row in range(GRID_SIZE):
    gz = row - (GRID_SIZE - 1) // 2
    coords = []
    for col in range(GRID_SIZE):
        x, y = pts[row][col]
        coords.append(f"{x:3d},{y:3d}")
    print(f"    .byte {', '.join(coords)}  ; gz={gz:+d}")

print()

print("; Vertical chains (9 columns × 9 points = 162 bytes)")
for col in range(GRID_SIZE):
    gx = col - (GRID_SIZE - 1) // 2
    coords = []
    for row in range(GRID_SIZE):
        x, y = pts[row][col]
        coords.append(f"{x:3d},{y:3d}")
    print(f"    .byte {', '.join(coords)}  ; gx={gx:+d}")
