#!/usr/bin/env python3
"""Generate height interpolation lookup table for edge-clamped grid vertices.

Table: 192 bytes, diff-major layout with stride 16.
  diff = 1..12 (height difference in h×8 units)
  offset = 0..15 (lerp_t >> 2, bin-centred)
  result = round((offset×4 + 2) × diff / 8) = ((2*offset+1)*diff+2)//4

Pre-scales by x8 so interpolation happens at world-coordinate resolution.
Max value = offset=15, diff=12 → 93.

Used by grid.s to correct the height of vertices clamped to the screen edge.
"""


def main():
    table = []
    for diff in range(1, 13):       # 1..12 (rows)
        for offset in range(16):    # 0..15 (columns)
            val = ((2 * offset + 1) * diff + 2) // 4
            table.append(val)

    assert len(table) == 192

    with open("interp_data.inc", "w") as f:
        f.write("; Height interpolation LUT (192 bytes)\n")
        f.write("; Generated by gen_interp.py\n")
        f.write("; Index: (diff-1)<<4 | offset, value: round((offset*4+2)*diff/8)\n")
        f.write("; diff = height difference (1..12), offset = lerp_t>>2 (0..15)\n\n")
        f.write("interp_lut:\n")
        for diff in range(12):
            base = diff * 16
            vals = ", ".join(f"${v:02X}" for v in table[base:base+16])
            f.write(f"    .byte {vals}  ; diff={diff+1}\n")

    print(f"Wrote interp_data.inc ({len(table)} bytes)")


if __name__ == "__main__":
    main()
