#!/usr/bin/env python3
"""Generate height interpolation lookup table for edge-clamped grid vertices.

Table: 256 bytes, indexed by (diff-1)*64 + offset
  diff = 1..4 (height difference between adjacent cells)
  offset = 0..63 (sub-cell position of clamped edge)
  result = round(offset * diff / 8) = pre-scaled world-coord delta

Pre-scales by x8 so interpolation happens at world-coordinate resolution
(8x finer granularity than height units). Max value = round(63*4/8) = 32.

Used by grid.s to correct the height of vertices clamped to the screen edge.
"""


def main():
    table = []
    for diff in range(1, 5):
        for offset in range(64):
            val = (offset * diff + 4) // 8  # pre-scaled world-coord delta
            table.append(val)

    assert len(table) == 256

    with open("interp_data.inc", "w") as f:
        f.write("; Height interpolation LUT (256 bytes)\n")
        f.write("; Generated by gen_interp.py\n")
        f.write("; Index: (|diff|-1)*64 + offset, value: round(offset * |diff| / 8)\n")
        f.write("; diff = height difference (1..4), offset = sub-cell position (0..63)\n\n")
        f.write("interp_lut:\n")
        for diff in range(4):
            f.write(f"    ; diff = {diff + 1}\n")
            for row in range(4):
                base = diff * 64 + row * 16
                vals = ", ".join(f"${v:02X}" for v in table[base:base+16])
                f.write(f"    .byte {vals}\n")

    print(f"Wrote interp_data.inc ({len(table)} bytes)")


if __name__ == "__main__":
    main()
