#!/usr/bin/env python3
"""
Testbench for 6502 line rasterizer — chain mode.
Draws chained line segments through the emulator and compares
against a Python reference Bresenham.
"""

import os, sys, random, subprocess

SCREEN_W = 128
SCREEN_H = 160
MASK_LEFT  = 0x2A
MASK_RIGHT = 0x15

SEED = 42


def reference_line(x0, y0, x1, y1):
    """
    Reference Bresenham matching the 6502 draw_line.
    Draws pixel_count pixels from (x0,y0) toward (x1,y1), NOT the endpoint.
    Returns set of (x, y).
    """
    pixels = set()
    dx = abs(x1 - x0)
    dy = abs(y1 - y0)

    if dx == 0 and dy == 0:
        return pixels  # zero-length: draw_line does nothing

    x_dir = 1 if x1 > x0 else (-1 if x1 < x0 else 0)
    y_dir = 1 if y1 > y0 else (-1 if y1 < y0 else 0)

    if dx >= dy:
        pixel_count = dx
        delta_major = dx
        delta_minor = dy
        error = (delta_major - delta_minor) & 0xFF
        x, y = x0, y0
        for _ in range(pixel_count):
            pixels.add((x, y))
            if error >= delta_minor:
                error = (error - delta_minor) & 0xFF
            else:
                error = (error - delta_minor + delta_major) & 0xFF
                y += y_dir
            x += x_dir
    else:
        pixel_count = dy
        delta_major = dy
        delta_minor = dx
        error = (delta_major - delta_minor) & 0xFF
        x, y = x0, y0
        for _ in range(pixel_count):
            pixels.add((x, y))
            if error >= delta_minor:
                error = (error - delta_minor) & 0xFF
            else:
                error = (error - delta_minor + delta_major) & 0xFF
                x += x_dir
            y += y_dir

    return pixels


def reference_chain(points):
    """
    Draw a chain of segments like draw_grid does:
    draw_line for each consecutive pair, then final pixel at last point.
    Uses union (AND/ORA overwrite) to match the 6502's coloured rendering.
    """
    pixels = set()
    for i in range(len(points) - 1):
        x0, y0 = points[i]
        x1, y1 = points[i + 1]
        seg_pixels = reference_line(x0, y0, x1, y1)
        pixels = pixels.union(seg_pixels)
    # Final pixel at endpoint
    final = points[-1]
    pixels.add(final)
    return pixels


def parse_ppm_pixels(path):
    """Parse 2x-upscaled PPM, return set of (x, y) at original resolution."""
    with open(path, 'rb') as f:
        magic = f.readline().strip()
        assert magic == b'P6', f"Bad PPM magic: {magic}"
        dims = f.readline().split()
        w, h = int(dims[0]), int(dims[1])
        f.readline()  # max val
        rgb = f.read()
    pixels = set()
    for py in range(0, h, 2):
        for px in range(0, w, 2):
            i = (py * w + px) * 3
            if rgb[i] or rgb[i+1] or rgb[i+2]:
                pixels.add((px // 2, py // 2))
    return pixels


def write_chain_data_inc(chains, path):
    """Write test_data.inc with chain data.
    Format: [num_points] [x0 y0] [x1 y1] ... then $FF sentinel.
    """
    with open(path, 'w') as f:
        f.write('; Auto-generated by test_raster.py\n')
        f.write('test_data:\n')
        for i, chain in enumerate(chains):
            pts_str = ' -> '.join(f'({x},{y})' for x, y in chain)
            f.write(f'    ; chain {i}: {pts_str}\n')
            f.write(f'    .byte {len(chain)}')
            for x, y in chain:
                f.write(f', ${x:02X},${y:02X}')
            f.write('\n')
        f.write('    .byte $FF              ; sentinel\n')


def build():
    r = subprocess.run(['ca65', '--cpu', '65C02', 'test_line.s', '-o', 'test_line.o'],
                       capture_output=True, text=True)
    if r.returncode != 0:
        print(f"Assembly failed:\n{r.stderr}")
        sys.exit(1)
    r = subprocess.run(['ld65', '-C', 'linker.cfg', 'test_line.o', '-o', 'test_line.bin'],
                       capture_output=True, text=True)
    if r.returncode != 0:
        print(f"Link failed:\n{r.stderr}")
        sys.exit(1)


def run_emulator(num_frames, dump_dir):
    os.makedirs(dump_dir, exist_ok=True)
    for f in os.listdir(dump_dir):
        os.remove(os.path.join(dump_dir, f))
    r = subprocess.run(
        ['./emu', 'test_line.bin', '--headless', str(num_frames),
         '--dump-frames', dump_dir],
        capture_output=True, timeout=300)
    if r.returncode != 0:
        print(f"Emulator failed (rc={r.returncode})")
        sys.exit(1)


def generate_random_chains(n, seed):
    """Generate n random chains with 3-9 points each."""
    rng = random.Random(seed)
    chains = []
    for _ in range(n):
        num_points = rng.randint(3, 9)
        chain = []
        for _ in range(num_points):
            chain.append((rng.randint(0, SCREEN_W - 1),
                          rng.randint(0, SCREEN_H - 1)))
        chains.append(chain)
    return chains


def main():
    # The specific chain from the grid + random chains
    grid_chain = [
        (6, 109), (21, 110), (35, 111), (50, 119),
        (64, 126), (78, 132), (93, 134), (107, 138), (122, 136)
    ]

    chains = []
    # Test grid chain subsets: 2 points through 9 points
    for n in range(2, len(grid_chain) + 1):
        chains.append(grid_chain[:n])
    # Add random chains
    chains += generate_random_chains(200, SEED)

    print(f"Testing {len(chains)} chains ({len(chains)-1} random + 1 grid chain)...")
    write_chain_data_inc(chains, 'test_data.inc')

    print("Building test_line.bin...")
    build()

    skip_frames = 10
    # Each chain: 1 pre-vsync + 1 draw frame + ~3 clear frames + 2 vsync waits = ~7 frames
    total_frames = skip_frames + len(chains) * 8 + 20
    dump_dir = '/tmp/test_line_frames'

    print(f"Running emulator for {total_frames} frames...")
    run_emulator(total_frames, dump_dir)

    frame_files = sorted(f for f in os.listdir(dump_dir) if f.endswith('.ppm'))
    print(f"Got {len(frame_files)} frame files")

    # Parse all frames for pixel content
    frame_pixels = []
    for fname in frame_files:
        px = parse_ppm_pixels(os.path.join(dump_dir, fname))
        frame_pixels.append((fname, px))

    # Segment into groups of non-empty frames separated by empty frames.
    # Take the frame with the MOST pixels in each group — handles both
    # partial draws (vsync during draw) and partial clears (vsync during clear).
    chain_frames = []
    group_best = None
    group_best_count = 0
    for fname, px in frame_pixels:
        if len(px) > 0:
            if len(px) > group_best_count:
                group_best = (fname, px)
                group_best_count = len(px)
        else:
            if group_best is not None:
                chain_frames.append(group_best)
                group_best = None
                group_best_count = 0
    if group_best is not None:
        chain_frames.append(group_best)

    print(f"Found {len(chain_frames)} chain frames for {len(chains)} chains")

    if len(chain_frames) == 0:
        print("ERROR: No chain frames found!")
        sys.exit(1)

    print()

    pass_count = 0
    fail_count = 0
    first_fails = []

    for t, chain in enumerate(chains):
        if t >= len(chain_frames):
            print(f"Ran out of frames at chain {t}")
            break

        fname, emu_pixels = chain_frames[t]
        ref_pixels = reference_chain(chain)

        if emu_pixels == ref_pixels:
            pass_count += 1
        else:
            fail_count += 1
            extra = emu_pixels - ref_pixels
            missing = ref_pixels - emu_pixels
            if len(first_fails) < 20:
                pts_str = '->'.join(f'({x},{y})' for x, y in chain)
                first_fails.append({
                    'test': t,
                    'chain': pts_str,
                    'num_segs': len(chain) - 1,
                    'ref_count': len(ref_pixels),
                    'emu_count': len(emu_pixels),
                    'extra': sorted(extra)[:10],
                    'missing': sorted(missing)[:10],
                })

    total = pass_count + fail_count
    print(f"\nResults: {pass_count} passed, {fail_count} failed out of {total}")

    if first_fails:
        print(f"\nFirst {len(first_fails)} failures:")
        for f in first_fails:
            label = "GRID" if f['test'] == 0 else f"rand"
            print(f"\n  Chain {f['test']} ({label}, {f['num_segs']} segs): "
                  f"ref={f['ref_count']}px emu={f['emu_count']}px")
            print(f"    {f['chain'][:120]}")
            if f['missing']:
                print(f"    Missing (in ref, not emu): {f['missing']}")
            if f['extra']:
                print(f"    Extra  (in emu, not ref): {f['extra']}")

    return 0 if fail_count == 0 else 1


if __name__ == '__main__':
    sys.exit(main())
