; test_line.s — Line rasterizer testbench
; Draws test lines one per frame for comparison against reference.
; Assembled with ca65: ca65 --cpu 65C02 test_line.s -o test_line.o
; Linked with ld65:    ld65 -C linker.cfg test_line.o -o test_line.bin

.setcpu "65C02"
.segment "CODE"

; === Hardware registers ===
CRTC_REG    = $FE00
CRTC_DAT    = $FE01
SYS_VIA_IFR = $FE4D

.include "raster_zp.inc"

; === Zero page: test harness ===
test_ptr        = $60       ; 2 bytes
chain_idx       = $62
seg_count       = $63
saved_y         = $64
saved_color     = $65

; === Constants ===
SCREEN_W    = 128
SCREEN_H    = 160

; =====================================================================
; Entry point ($0800)
; =====================================================================

entry:
    SEI

    ; Set CRTC to show $3000 (R12=$06, R13=$00)
    LDA #12
    STA CRTC_REG
    LDA #$06
    STA CRTC_DAT
    LDA #13
    STA CRTC_REG
    LDA #$00
    STA CRTC_DAT

    ; Clear screen buffer at $3000 (40 pages: $3000-$57FF)
    LDA #0
    TAY
    LDX #$30
    STX base+1
    STY base
@clear_page:
    STA (base),Y
    INY
    BNE @clear_page
    INC base+1
    LDX base+1
    CPX #$58
    BNE @clear_page

    ; Set screen page
    LDA #$30
    STA screen_page

    ; Set line colour to white
    LDA #$15
    STA saved_color

    ; Initialize test pointer
    LDA #<test_data
    STA test_ptr
    LDA #>test_data
    STA test_ptr+1

    ; Clear any pending vsync
    LDA #$02
    STA SYS_VIA_IFR

; === Main test loop — draws chains ===
; Format: [num_points] [x0 y0] [x1 y1] [x2 y2] ... [sentinel $FF]
; Each chain: init_base at first point, then draw_line chained for each segment,
; final pixel at end. One vsync per chain to capture the frame.
test_loop:
    ; Read chain header: number of points
    LDY #0
    LDA (test_ptr),Y
    CMP #$FF
    BNE @has_chain
    JMP test_done
@has_chain:
    ; A = num_points, segments = num_points - 1
    SEC
    SBC #1
    STA seg_count

    ; Sync to frame boundary so drawing has full 40000 cycles
    JSR wait_vsync

    ; Load first point
    LDY #1
    LDA (test_ptr),Y
    STA x0
    INY
    LDA (test_ptr),Y
    STA y0
    JSR init_base           ; set base, Y from (x0, y0)
    LDA #3
    STA chain_idx           ; byte offset of next endpoint in chain

@seg_loop:
    ; Save sub-row Y from previous segment / init_base
    STY saved_y
    ; Load next endpoint
    LDY chain_idx
    LDA (test_ptr),Y
    STA x1
    INY
    LDA (test_ptr),Y
    STA y1
    INY
    STY chain_idx
    ; Restore sub-row Y before draw_line (it does PHY first thing)
    LDY saved_y
    LDA saved_color
    JSR draw_line           ; draw segment, chaining state
    ; Endpoint becomes start of next segment
    LDA x1
    STA x0
    LDA y1
    STA y0
    DEC seg_count
    BNE @seg_loop

    ; Draw final pixel of chain
    LDA x0
    LSR A                   ; bit 0 → carry
    LDA (base),Y
    BCS @right_final
    AND #$D5
    ORA color_left
    BRA @store_final
@right_final:
    AND #$EA
    ORA color_right
@store_final:
    STA (base),Y

    ; --- Wait for vsync (frame dump captures the drawn chain) ---
    JSR wait_vsync

    ; --- Clear screen for next chain ---
    JSR clear_screen
    JSR wait_vsync          ; ensure blank is captured
    JSR wait_vsync          ; extra sync for safety

    ; --- Advance test_ptr past this chain ---
    ; Chain size = 1 (header) + num_points * 2
    LDY #0
    LDA (test_ptr),Y        ; num_points
    ASL A                    ; * 2
    INC A                    ; + 1 (header byte)
    CLC
    ADC test_ptr
    STA test_ptr
    BCS @ptr_carry
    JMP test_loop
@ptr_carry:
    INC test_ptr+1
    JMP test_loop

test_done:
    JMP test_done

; =====================================================================
; Wait for one vsync
; =====================================================================
wait_vsync:
    ; Clear pending
    LDA #$02
    STA SYS_VIA_IFR
@wait:
    LDA SYS_VIA_IFR
    AND #$02
    BEQ @wait
    RTS

; =====================================================================
; Clear screen buffer at $3000-$57FF
; =====================================================================
clear_screen:
    LDA #0
    TAY
    LDX #$30
    STX base+1
    STY base
@loop:
    STA (base),Y
    INY
    BNE @loop
    INC base+1
    LDX base+1
    CPX #$58
    BNE @loop
    RTS

.include "raster.s"

; =====================================================================
; Test data — generated by testbench.py
; =====================================================================
.include "test_data.inc"
