#!/usr/bin/env python3
"""
Validate raster.s Bresenham line drawer against a Python reference.

Assembles a test harness (ca65+ld65), runs it through w65c02s_runner,
extracts pixels from the stripe-based framebuffer, and compares with
a reference Bresenham implementation.
"""

import os
import random
import struct
import subprocess
import sys
import tempfile

TOOLS_DIR  = os.path.join(os.path.dirname(os.path.abspath(__file__)), "tools")
RUNNER     = os.path.join(TOOLS_DIR, "w65c02s_runner")
LINKER_CFG = os.path.join(TOOLS_DIR, "linker_65c02.cfg")
RASTER_S   = os.path.join(os.path.dirname(os.path.abspath(__file__)), "raster.s")

SCREEN_BASE_HI = 0x20          # screen at $2000
SCREEN_BASE    = SCREEN_BASE_HI << 8


# ── Reference Bresenham ──────────────────────────────────────────────

def reference_bresenham(x0, y0, x1, y1):
    """
    Match the assembly's draw order.  For upward lines (y0 >= y1) we
    traverse left-to-right.  For downward lines (y1 > y0) the assembly
    swaps endpoints and draws right-to-left (backward), so the
    Bresenham step decisions land at different x positions.  We
    replicate that here.
    Requires  x1 >= x0,  (x1-x0) >= abs(y0-y1).
    """
    dx = x1 - x0
    dy = abs(y0 - y1)
    going_down = y1 > y0
    pixels = set()
    d = dx - dy
    if going_down:
        # Backward traversal: start at (x1, y1), walk left, y upward
        y = y1
        for i in range(dx + 1):
            pixels.add((x1 - i, y))
            d -= dy
            if d < 0:
                d += dx
                y -= 1
    else:
        # Forward traversal: start at (x0, y0), walk right, y upward
        y = y0
        for x in range(x0, x1 + 1):
            pixels.add((x, y))
            d -= dy
            if d < 0:
                d += dx
                y -= 1
    return pixels


# ── Screen memory extraction ─────────────────────────────────────────

def pixel_addr_and_mask(x, y):
    """Return (address, bitmask) for pixel (x,y) in the stripe layout."""
    stripe = y >> 3
    row    = y & 7
    col    = x & 0xF8
    addr   = (SCREEN_BASE_HI + stripe) * 256 + col + row
    mask   = 0x80 >> (x & 7)
    return addr, mask

def extract_pixels(mem, x_min, x_max, y_min, y_max):
    """Return set of (x,y) for all set pixels in the given bounding box."""
    pixels = set()
    for y in range(y_min, y_max + 1):
        for x in range(x_min, x_max + 1):
            addr, mask = pixel_addr_and_mask(x, y)
            if mem[addr] & mask:
                pixels.add((x, y))
    return pixels

def extract_all_pixels(mem):
    """Return set of (x,y) for ALL set pixels in screen memory."""
    pixels = set()
    for stripe in range(32):          # 256/8 = 32 stripes
        page = SCREEN_BASE_HI + stripe
        base = page * 256
        for col in range(0, 256, 8):  # 32 byte columns
            for row in range(8):
                byte_val = mem[base + col + row]
                if byte_val:
                    for bit in range(8):
                        if byte_val & (0x80 >> bit):
                            x = col + bit
                            y = stripe * 8 + row
                            pixels.add((x, y))
    return pixels


# ── Test harness assembly generation ─────────────────────────────────

HARNESS_TEMPLATE = """\
; Test harness — generated by validate_bresenham.py
.feature leading_dot_in_identifiers

.segment "CODE"

; Temp ZP storage (doesn't collide with raster.s $70-$84)
save_d   = $60
save_y   = $61
jmp_lo   = $62
jmp_hi   = $63

main:
    CLD                         ; ensure binary mode
    ; ── set screen page and const_ff ──
    LDA #$FF
    STA $77                     ; const_ff
    LDA #${screen_hi:02X}
    STA $84                     ; screen_page

    ; ── set coordinates ──
    LDA #{x0}
    STA $80                     ; x0
    LDA #{y0}
    STA $81                     ; y0
    LDA #{x1}
    STA $82                     ; x1
    LDA #{y1}
    STA $83                     ; y1

    ; ── call setup_line ──
    JSR setup_line              ; returns X=d, Y=row, C=1

    ; ── save returned state ──
    STX save_d
    STY save_y

    ; ── look up entry point ──
    LDA $80                     ; x0
    AND #$07
    ASL A                       ; *2 for word index
    TAX
    LDA entry_table,X
    STA jmp_lo
    LDA entry_table+1,X
    STA jmp_hi

    ; ── push return address so draw_line's RTS lands at halt ──
    LDA #>(halt-1)
    PHA
    LDA #<(halt-1)
    PHA

    ; ── restore state and jump ──
    LDY save_y
    LDX save_d
    SEC                         ; C=1 for first SBC
    JMP (jmp_lo)                ; enter the draw loop

halt:
    STP                         ; $DB — stop the 65C02

; ── include the code under test ──
.include "raster.s"
"""

def generate_harness(x0, y0, x1, y1):
    return HARNESS_TEMPLATE.format(
        screen_hi=SCREEN_BASE_HI,
        x0=x0, y0=y0, x1=x1, y1=y1,
    )


# ── Build & run ──────────────────────────────────────────────────────

def assemble_and_run(harness_src, tmpdir):
    """Assemble, link, run, and return the 64 KB memory image."""
    src_path = os.path.join(tmpdir, "harness.s")
    obj_path = os.path.join(tmpdir, "harness.o")
    bin_path = os.path.join(tmpdir, "harness.bin")
    mem_path = os.path.join(tmpdir, "mem.bin")

    with open(src_path, "w") as f:
        f.write(harness_src)

    # Assemble (use -I so .include "raster.s" finds the source)
    raster_dir = os.path.dirname(RASTER_S)
    r = subprocess.run(
        ["ca65", "--cpu", "65C02", "-I", raster_dir, "-o", obj_path, src_path],
        capture_output=True, text=True,
    )
    if r.returncode != 0:
        raise RuntimeError(f"ca65 failed:\n{r.stderr}")

    # Link
    r = subprocess.run(
        ["ld65", "-C", LINKER_CFG, "-o", bin_path, obj_path],
        capture_output=True, text=True,
    )
    if r.returncode != 0:
        raise RuntimeError(f"ld65 failed:\n{r.stderr}")

    # Run
    r = subprocess.run(
        [RUNNER, bin_path, mem_path],
        capture_output=True, text=True,
    )
    if r.returncode not in (0, 2):
        raise RuntimeError(f"runner failed (rc={r.returncode}):\n{r.stderr}")
    if r.returncode == 2:
        raise RuntimeError(f"runner hit cycle limit (CPU did not halt):\n{r.stderr}")

    with open(mem_path, "rb") as f:
        mem = f.read()
    if len(mem) != 65536:
        raise RuntimeError(f"memory dump is {len(mem)} bytes, expected 65536")

    return mem


# ── Visualisation ────────────────────────────────────────────────────

def visual_diff(emu_pixels, ref_pixels, x0, y0, x1, y1):
    """
    Return a string grid:
      '#' = both      'E' = emulator only      'R' = reference only
      '.' = neither
    """
    x_lo = min(x0, x1)
    x_hi = max(x0, x1)
    y_lo = min(y0, y1)
    y_hi = max(y0, y1)
    lines = []
    # Header with x coords (ones digit)
    hdr = "     "
    for x in range(x_lo, x_hi + 1):
        hdr += str(x % 10)
    lines.append(hdr)
    for y in range(y_lo, y_hi + 1):
        row = f"y={y:3d} "
        for x in range(x_lo, x_hi + 1):
            e = (x, y) in emu_pixels
            r = (x, y) in ref_pixels
            if e and r:
                row += "#"
            elif e:
                row += "E"
            elif r:
                row += "R"
            else:
                row += "."
        lines.append(row)
    return "\n".join(lines)


# ── Test cases ───────────────────────────────────────────────────────

TEST_CASES = [
    # (name, x0, y0, x1, y1)
    ("horizontal 0-15",              0,   7,  15,  7),
    ("horizontal 8-23",              8,  10,  23, 10),
    ("shallow 0,15 -> 20,10",        0,  15,  20, 10),
    ("45-degree 0,7 -> 7,0",         0,   7,   7,  0),
    ("45-degree 3,15 -> 10,8",       3,  15,  10,  8),
    ("single byte 0,7 -> 5,4",       0,   7,   5,  4),
    ("single byte 2,3 -> 6,1",       2,   3,   6,  1),
    ("multi-stripe 0,23 -> 30,5",    0,  23,  30,  5),
    ("byte-aligned 8,15 -> 23,8",    8,  15,  23,  8),
    ("wide shallow 0,10 -> 39,5",    0,  10,  39,  5),
    ("one-pixel dy 0,8 -> 15,7",     0,   8,  15,  7),
    ("cross-stripe 0,8 -> 10,0",     0,   8,  10,  0),
    ("long line 0,31 -> 63,8",       0,  31,  63,  8),
    ("mid-byte start 3,10 -> 18,4",  3,  10,  18,  4),
    ("end on byte 0,15 -> 7,10",     0,  15,   7, 10),
    ("down shallow 0,5 -> 20,10",        0,   5,  20, 10),
    ("down 45-degree 0,0 -> 7,7",        0,   0,   7,  7),
    ("down single byte 0,4 -> 5,7",      0,   4,   5,  7),
    ("down multi-stripe 0,5 -> 30,23",   0,   5,  30, 23),
    ("down cross-stripe 0,0 -> 10,8",    0,   0,  10,  8),
    ("down one-pixel dy 0,7 -> 15,8",    0,   7,  15,  8),
    ("down long line 0,8 -> 63,31",      0,   8,  63, 31),
]


def generate_soak_cases(count=200, seed=42):
    """Generate random test cases with dx, dy up to 255."""
    rng = random.Random(seed)
    cases = []
    for i in range(count):
        # dx in 1..255
        dx = rng.randint(1, 255)
        # dy in 0..dx (shallow octant)
        dy = rng.randint(0, dx)
        # x0 anywhere that leaves room for dx
        x0 = rng.randint(0, 255 - dx)
        x1 = x0 + dx
        # Pick direction: up or down
        if rng.random() < 0.5:
            # Upward: y0 >= y1, y0 = y1 + dy
            y1 = rng.randint(0, 255 - dy)
            y0 = y1 + dy
        else:
            # Downward: y1 > y0, y1 = y0 + dy
            y0 = rng.randint(0, 255 - dy)
            y1 = y0 + dy
        name = f"soak {i}: ({x0},{y0})->({x1},{y1})"
        cases.append((name, x0, y0, x1, y1))
    return cases


# ── Main ─────────────────────────────────────────────────────────────

def main():
    # Ensure runner is built
    if not os.path.isfile(RUNNER):
        print(f"Building {RUNNER}...")
        r = subprocess.run(
            ["cc", "-O2", "-o", RUNNER,
             os.path.join(TOOLS_DIR, "w65c02s_runner.c"), "-I", TOOLS_DIR],
            capture_output=True, text=True,
        )
        if r.returncode != 0:
            print(f"Failed to build runner:\n{r.stderr}", file=sys.stderr)
            sys.exit(1)

    passes = 0
    fails  = 0

    all_cases = TEST_CASES + generate_soak_cases()

    with tempfile.TemporaryDirectory(prefix="raster_test_") as tmpdir:
        for name, x0, y0, x1, y1 in all_cases:
            dx = x1 - x0
            dy = abs(y0 - y1)
            tag = f"({x0},{y0})->({x1},{y1}) dx={dx} dy={dy}"
            print(f"  {name:40s} {tag} ... ", end="", flush=True)

            # Sanity check test params
            assert x1 >= x0, f"x1 < x0 in test '{name}'"
            assert dx >= dy, f"dx < dy in test '{name}'"

            ref = reference_bresenham(x0, y0, x1, y1)

            src = generate_harness(x0, y0, x1, y1)
            try:
                mem = assemble_and_run(src, tmpdir)
            except RuntimeError as e:
                print(f"BUILD/RUN ERROR\n{e}")
                fails += 1
                continue

            emu = extract_all_pixels(mem)

            if emu == ref:
                print("PASS")
                passes += 1
            else:
                print("FAIL")
                fails += 1
                print(visual_diff(emu, ref, x0, y0, x1, y1))
                only_emu = emu - ref
                only_ref = ref - emu
                if only_emu:
                    print(f"    Emulator-only pixels: {sorted(only_emu)}")
                if only_ref:
                    print(f"    Reference-only pixels: {sorted(only_ref)}")
                print()

    print(f"\n{'='*60}")
    print(f"  {passes} passed, {fails} failed, {passes+fails} total")
    if fails:
        sys.exit(1)
    else:
        print("  All tests passed!")


if __name__ == "__main__":
    main()
